# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 13:22
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=300)),
                ('user', models.CharField(max_length=60, verbose_name=django.contrib.auth.models.User)),
                ('timecomment', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['comment'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('image_name', models.CharField(max_length=60)),
                ('image_caption', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('postdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['image'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(max_length=250)),
                ('user', models.CharField(max_length=60, verbose_name=django.contrib.auth.models.User)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instagram.Image'),
        ),
    ]
