# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
